<Project>
  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <Copyright>Ilya Belyanskiy 2025</Copyright>
    <Authors>Belyansky Ilya</Authors>
    <PackageProjectUrl>https://github.com/win7user10/Laraue.Apps.LearnLanguage</PackageProjectUrl>
    <!-- Designate all projects as non-package projects by default -->
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  
  <PropertyGroup>
    <Linq2DbVersion>6.0.0</Linq2DbVersion>
    <LaraueTelegramNetVersion>4.0.9</LaraueTelegramNetVersion>
    <LaraueCoreDataAccessVersion>10.4.0</LaraueCoreDataAccessVersion>
    <LaraueCoreDateTimeVersion>10.0.0</LaraueCoreDateTimeVersion>
    <EfCoreVersion>10.0.0</EfCoreVersion>
    <NpgsqlEfCoreVersion>10.0.0</NpgsqlEfCoreVersion>
    <EfCoreNamingConventionsVersion>10.0.0-rc.2</EfCoreNamingConventionsVersion>
    <LaraueCoreOllamaVersion>2.1.4</LaraueCoreOllamaVersion>
    <TelegramBotVersion>22.7.0</TelegramBotVersion>
  </PropertyGroup>
</Project>