<Project>
  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <Copyright>Ilya Belyanskiy 2025</Copyright>
    <Authors>Belyansky Ilya</Authors>
    <PackageProjectUrl>https://github.com/win7user10/Laraue.Apps.LearnLanguage</PackageProjectUrl>
    <!-- Designate all projects as non-package projects by default -->
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  
  <PropertyGroup>
    <Linq2DbVersion>6.3.0</Linq2DbVersion>
    <LaraueTelegramNetVersion>4.9.1</LaraueTelegramNetVersion>
    <LaraueCoreDataAccessVersion>10.8.0</LaraueCoreDataAccessVersion>
    <LaraueCoreDateTimeVersion>10.0.0</LaraueCoreDateTimeVersion>
    <EfCoreVersion>10.0.0</EfCoreVersion>
    <NpgsqlEfCoreVersion>10.0.0</NpgsqlEfCoreVersion>
    <EfCoreNamingConventionsVersion>10.0.1</EfCoreNamingConventionsVersion>
    <LaraueCoreOllamaVersion>1.0.0</LaraueCoreOllamaVersion>
    <TelegramBotVersion>22.7.0</TelegramBotVersion>
    <OpenTelemetryExtensionsHostingVersion>1.18.0</OpenTelemetryExtensionsHostingVersion>
    <OpenTelemetryExporterPrometheusAspNetCoreVersion>1.18.0-beta.1</OpenTelemetryExporterPrometheusAspNetCoreVersion>
    <OpenTelemetryInstrumentationAspNetCoreVersion>1.18.0</OpenTelemetryInstrumentationAspNetCoreVersion>
    <OpenTelemetryInstrumentationHttpVersion>1.18.0</OpenTelemetryInstrumentationHttpVersion>
    <OpenTelemetryInstrumentationRuntimeVersion>1.18.0</OpenTelemetryInstrumentationRuntimeVersion>
  </PropertyGroup>
</Project>