//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.LearnLanguage.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laraue.Apps.LearnLanguage.Services.Resources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn words by Common European Framework of Reference for Languages, e.g. A1, A2, B1 etc..
        /// </summary>
        internal static string Mode_CefrLevel_Description {
            get {
                return ResourceManager.GetString("Mode_CefrLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn words in random order.
        /// </summary>
        internal static string Mode_Random_Description {
            get {
                return ResourceManager.GetString("Mode_Random_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn words alphabetically from A to Z.
        /// </summary>
        internal static string Mode_Sequential_Description {
            get {
                return ResourceManager.GetString("Mode_Sequential_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn words by the specified category: family, body etc..
        /// </summary>
        internal static string Mode_Topic_Description {
            get {
                return ResourceManager.GetString("Mode_Topic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the mode.
        /// </summary>
        internal static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
    }
}
