//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.LearnLanguage.AppServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laraue.Apps.LearnLanguage.AppServices.Resources.Mode", typeof(Mode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty: {0}.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string Difficulty_Easy {
            get {
                return ResourceManager.GetString("Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Difficulty_Hard {
            get {
                return ResourceManager.GetString("Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string Difficulty_Impossible {
            get {
                return ResourceManager.GetString("Difficulty_Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very hard.
        /// </summary>
        public static string Difficulty_Medium {
            get {
                return ResourceManager.GetString("Difficulty_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impossible.
        /// </summary>
        public static string Difficulty_VeryHard {
            get {
                return ResourceManager.GetString("Difficulty_VeryHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: Marked 🔍.
        /// </summary>
        public static string Filter_Marked {
            get {
                return ResourceManager.GetString("Filter_Marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: None 🔍.
        /// </summary>
        public static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: Not Learned 🔍.
        /// </summary>
        public static string Filter_NotLearned {
            get {
                return ResourceManager.GetString("Filter_NotLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide translations 🙈.
        /// </summary>
        public static string HideTranslations {
            get {
                return ResourceManager.GetString("HideTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned: {0} day(s) ago.
        /// </summary>
        public static string Learned {
            get {
                return ResourceManager.GetString("Learned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Lists.
        /// </summary>
        public static string ListMode {
            get {
                return ResourceManager.GetString("ListMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all words.
        /// </summary>
        public static string ListModeDescription {
            get {
                return ResourceManager.GetString("ListModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next ➡.
        /// </summary>
        public static string Navigation_Next {
            get {
                return ResourceManager.GetString("Navigation_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous ⬅.
        /// </summary>
        public static string Navigation_Previous {
            get {
                return ResourceManager.GetString("Navigation_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened word:.
        /// </summary>
        public static string OpenedWord {
            get {
                return ResourceManager.GetString("OpenedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open word:.
        /// </summary>
        public static string OpenWord {
            get {
                return ResourceManager.GetString("OpenWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated: {0} day(s) ago.
        /// </summary>
        public static string Repeated {
            get {
                return ResourceManager.GetString("Repeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language pair. You also can set the preferred language pair in settings to select the same pair always..
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the mode.
        /// </summary>
        public static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show translations 👁.
        /// </summary>
        public static string ShowTranslations {
            get {
                return ResourceManager.GetString("ShowTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic: {0}.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation -&gt; Word.
        /// </summary>
        public static string ViewMode_TranslationToWord {
            get {
                return ResourceManager.GetString("ViewMode_TranslationToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word -&gt; Translation.
        /// </summary>
        public static string ViewMode_WordToTranslation {
            get {
                return ResourceManager.GetString("ViewMode_WordToTranslation", resourceCulture);
            }
        }
    }
}
