//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.LearnLanguage.AppServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuizMode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuizMode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laraue.Apps.LearnLanguage.AppServices.Resources.QuizMode", typeof(QuizMode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Mode.
        /// </summary>
        public static string ButtonName {
            get {
                return ResourceManager.GetString("ButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language pair.
        /// </summary>
        public static string ChangeLanguagePair {
            get {
                return ResourceManager.GetString("ChangeLanguagePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change topic.
        /// </summary>
        public static string ChangeTopic {
            get {
                return ResourceManager.GetString("ChangeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the suggested word in quiz mode.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish quiz.
        /// </summary>
        public static string FinishQuiz {
            get {
                return ResourceManager.GetString("FinishQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language pair.
        /// </summary>
        public static string LanguagePair {
            get {
                return ResourceManager.GetString("LanguagePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned.
        /// </summary>
        public static string Learned {
            get {
                return ResourceManager.GetString("Learned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect!.
        /// </summary>
        public static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question options count.
        /// </summary>
        public static string QuestionOptionsCount {
            get {
                return ResourceManager.GetString("QuestionOptionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions will be asked.
        /// </summary>
        public static string QuestionsWillBeAsked {
            get {
                return ResourceManager.GetString("QuestionsWillBeAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [+].
        /// </summary>
        public static string QuizAnswer_Correct {
            get {
                return ResourceManager.GetString("QuizAnswer_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [-].
        /// </summary>
        public static string QuizAnswer_Incorrect {
            get {
                return ResourceManager.GetString("QuizAnswer_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [s].
        /// </summary>
        public static string QuizAnswer_Skipped {
            get {
                return ResourceManager.GetString("QuizAnswer_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz finished.
        /// </summary>
        public static string QuizFinishedTitle {
            get {
                return ResourceManager.GetString("QuizFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz is ready to start.
        /// </summary>
        public static string QuizReady {
            get {
                return ResourceManager.GetString("QuizReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select topic for the quiz.
        /// </summary>
        public static string SelectQuizTopic {
            get {
                return ResourceManager.GetString("SelectQuizTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipButtonName {
            get {
                return ResourceManager.GetString("SkipButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonName {
            get {
                return ResourceManager.GetString("StartButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats for the selected criteria.
        /// </summary>
        public static string StatsForTheCurrentCriteria {
            get {
                return ResourceManager.GetString("StatsForTheCurrentCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total questions by current criteria.
        /// </summary>
        public static string TotalQuestionsByCriteria {
            get {
                return ResourceManager.GetString("TotalQuestionsByCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total stat.
        /// </summary>
        public static string TotalStat {
            get {
                return ResourceManager.GetString("TotalStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the translation for.
        /// </summary>
        public static string TranslateWord {
            get {
                return ResourceManager.GetString("TranslateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win streak.
        /// </summary>
        public static string WinStreak {
            get {
                return ResourceManager.GetString("WinStreak", resourceCulture);
            }
        }
    }
}
