//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laraue.Apps.LearnLanguage.AppServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuizMode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuizMode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laraue.Apps.LearnLanguage.AppServices.Resources.QuizMode", typeof(QuizMode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} more.
        /// </summary>
        public static string AndMore {
            get {
                return ResourceManager.GetString("AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 New Quiz.
        /// </summary>
        public static string ButtonName {
            get {
                return ResourceManager.GetString("ButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEFR Levels.
        /// </summary>
        public static string CefrLevel {
            get {
                return ResourceManager.GetString("CefrLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎓 CEFR Levels.
        /// </summary>
        public static string CefrLevelWithIcon {
            get {
                return ResourceManager.GetString("CefrLevelWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language pair.
        /// </summary>
        public static string ChangeLanguagePair {
            get {
                return ResourceManager.GetString("ChangeLanguagePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Correct.
        /// </summary>
        public static string CorrectAnswers {
            get {
                return ResourceManager.GetString("CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game where the correct translation for the suggested word should be selected.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Finish quiz.
        /// </summary>
        public static string FinishQuiz {
            get {
                return ResourceManager.GetString("FinishQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Incorrect.
        /// </summary>
        public static string IncorrectAnswers {
            get {
                return ResourceManager.GetString("IncorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguagePair {
            get {
                return ResourceManager.GetString("LanguagePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔷 Learned.
        /// </summary>
        public static string Learned {
            get {
                return ResourceManager.GetString("Learned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meanings.
        /// </summary>
        public static string Meanings {
            get {
                return ResourceManager.GetString("Meanings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall progress.
        /// </summary>
        public static string OverallProgress {
            get {
                return ResourceManager.GetString("OverallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Perfect round! All answers correct!.
        /// </summary>
        public static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question options count.
        /// </summary>
        public static string QuestionOptionsCount {
            get {
                return ResourceManager.GetString("QuestionOptionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string QuestionsWillBeAsked {
            get {
                return ResourceManager.GetString("QuestionsWillBeAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅.
        /// </summary>
        public static string QuizAnswer_Correct {
            get {
                return ResourceManager.GetString("QuizAnswer_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌.
        /// </summary>
        public static string QuizAnswer_Incorrect {
            get {
                return ResourceManager.GetString("QuizAnswer_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏭.
        /// </summary>
        public static string QuizAnswer_Skipped {
            get {
                return ResourceManager.GetString("QuizAnswer_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz results.
        /// </summary>
        public static string QuizFinishedTitle {
            get {
                return ResourceManager.GetString("QuizFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 Quiz is ready.
        /// </summary>
        public static string QuizReady {
            get {
                return ResourceManager.GetString("QuizReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏭ Skip.
        /// </summary>
        public static string SkipButtonName {
            get {
                return ResourceManager.GetString("SkipButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏭ Skipped.
        /// </summary>
        public static string SkippedAnswers {
            get {
                return ResourceManager.GetString("SkippedAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 Start Quiz.
        /// </summary>
        public static string StartButtonName {
            get {
                return ResourceManager.GetString("StartButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats for the selected criteria.
        /// </summary>
        public static string StatsForTheCurrentCriteria {
            get {
                return ResourceManager.GetString("StatsForTheCurrentCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session.
        /// </summary>
        public static string ThisSession {
            get {
                return ResourceManager.GetString("ThisSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏷 Topics.
        /// </summary>
        public static string TopicsWithIcon {
            get {
                return ResourceManager.GetString("TopicsWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You progress for these settings.
        /// </summary>
        public static string TotalQuestionsByCriteria {
            get {
                return ResourceManager.GetString("TotalQuestionsByCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total stat.
        /// </summary>
        public static string TotalStat {
            get {
                return ResourceManager.GetString("TotalStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the translation for.
        /// </summary>
        public static string TranslateWord {
            get {
                return ResourceManager.GetString("TranslateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win streak.
        /// </summary>
        public static string WinStreak {
            get {
                return ResourceManager.GetString("WinStreak", resourceCulture);
            }
        }
    }
}
