# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Upload
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
       host: ${{ secrets.SSH_HOST }} # "example.com"
       port: ${{ secrets.SSH_PORT }} # 22
       user: ${{ secrets.SSH_USER }} # "user"
       password: ${{ secrets.SSH_PASSWORD }} # "password"
       local: Laraue.Apps.LearnLanguage.Host/bin/Release/net9.0/*
       remote: "/home/laraue/backend-learn-language"
       post_upload: echo "Uploaded successfully"
